### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by AKeeganDev** [Dangelo-JAN/KA_Show_Reviews#81]
Hello, here is a link to our KanBan:
https://github.com/Dangelo-JAN/KA_Show_Reviews/projects/2

Our coding partner group has only 2 people, myself and Dangelo.

Thank you!

**Comment by t-yanick** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments below and under the review._
- [ ] Since there are only two of you in this group, all cards with the `Student C suffix` on the template should removed, kindly delete all cards labelled `Student C` as you are not going to implement those tasks. The total number of cards on the board should be equals to 15. 
- [ ] Please kindly make sure all cards are assigned to team members, and in a fair way. You have to decide who is `Student A` and `Student B`, so each card with `Student A` in its title should always be assigned to the same student (same to `Student B).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-labana** [comment]
Hi team, 

Excellent work so far! 👌
You have implemented almost all the required features and you board is complete. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [ ] Each card should be assigned to at least a team member. Currently, all card have an assignee status of `No one assigned`. Kindly update your project board.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by nicupop729** [comment]
# STATUS: APPROVED :green_circle: :clap: 

Hi @Dangelo-JAN & @AKeeganDev>, 

Your project is complete! :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/l4EpblDY4msVtKAOk/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
